# Generated by Django 4.2.3 on 2023-07-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_summary_alter_language_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='publisher',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(max_length=300),
        ),
    ]
