# Generated by Django 4.2.3 on 2023-07-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_publisher_alter_bookinstance_imprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='publisher',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(max_length=400),
        ),
    ]
